name: Translator.io Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  lint: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
    - name: Install dependencies
      run: npm install
    - name: Lint code
      run: npm run lint
  
