name: Translator.io Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x, 20.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
    - name: Install dependencies
      run: npm install
    - name: Build app
      run: npm run build
    - name: Lint code
      run: npm run lint
